# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ebf7711bffe0ed2b048a3d732e7950f80e325a01c8c867774c1274768c7e11393228c02f0ef0beccaff3fa40ea037e878049286a289de6dd3d3e7c1a9fd17be

test:
  secret_key_base: 4a2792afd3e9e133b9a3cb7b234491a7f34e7593b38c6e0f3d824c09e5b5f6ecb52ae239e5b66b2097ae0ce3d027a38553e085b5675ec4e7dd47d38d55277165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
